"use client";


import "@/app/globals.css";
import { NextThemeProviders } from "../context/providers";
// import { Toaster } from "react-hot-toast";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/toaster";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body
        className={`antialiased flex justify-center items-center w-screen h-screen`}
      >
        <QueryClientProvider client={queryClient}>
          <NextThemeProviders>{children}</NextThemeProviders>
        </QueryClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
