import type { Metadata } from "next";
// import localFont from "next/font/local";
import "@/app/globals.css";
import { NextThemeProviders } from "../context/providers";
import { Toaster } from "react-hot-toast";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// import { ThemeProvider } from "next-themes";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body
        className={`antialiased flex justify-center items-center w-screen h-screen`}
      >
        <QueryClientProvider client={queryClient}>
          <NextThemeProviders>
            {children}
            <Toaster />
          </NextThemeProviders>
        </QueryClientProvider>
      </body>
    </html>
  );
}
