import type { Metadata } from "next";

import "@/app/globals.css";
import { NextThemeProviders } from "../context/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <NextThemeProviders>{children}</NextThemeProviders>
      </body>
    </html>
  );
}
